company/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path('home/', views.home, name='home'),
    path('pw_change/', views.pw_change, name='pw_change'),
    path('company_list/', views.company_list.as_view(), name='company_list'),
    path('company_add/', views.company_add.as_view(), name='company_add'),
    path('company_update/<int:pk>', views.company_update.as_view(), name='company_update'),
    path('company_detail/<int:pk>', views.company_detail.as_view(), name='company_detail'),
    path('profile_add/<int:cpk>', views.profile_add.as_view(), name='profile_add'),
    path('profile_update/<int:cpk>/<int:pk>', views.profile_update.as_view(), name='profile_update'),
    path('profile_detail/<int:pk>', views.profile_detail.as_view(), name='profile_detail'),
    path('project_list/', views.project_list.as_view(), name='project_list'),
    path('project_add/', views.project_add.as_view(), name='project_add'),
    path('project_update/<int:pk>', views.project_update.as_view(), name='project_update'),
    path('project_detail/<int:pk>', views.project_detail.as_view(), name='project_detail'),
    path('report_list/', views.report_list.as_view(), name='report_list'),
    path('report_add/', views.report_add.as_view(), name='report_add'),
    path('report_update/<int:pk>', views.report_update.as_view(), name='report_update'),
    path('report_detail/<int:pk>', views.report_detail.as_view(), name='report_detail'),
    path('report_check_list/', views.report_check_list.as_view(), name='report_check_list'),
    path('report_check/<int:pk>', views.report_check, name='report_check'),
    path('report_check_detail/<int:pk>', views.report_check_detail.as_view(), name='report_check_detail'),
]

openaifab/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings # new
from django.conf.urls.static import static # new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('company/', include('company.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]
#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/company/home')),
]

# Use static() to add url mapping to serve static files during development (only)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

company/models.py
from django.db import models
from django.urls import reverse

#customer company list
class company(models.Model):
    name = models.CharField(max_length=32)
    address = models.CharField(max_length=32)
    COMPANY_TYPE = (
        ('a', '媒體業'),
        ('b', '服務業'),
        ('c', 'AI公司'),
        ('d', '政府單位'),
        ('e', '教育機構'),
        ('z', '其他'),
    )
    type = models.CharField(max_length=1, choices=COMPANY_TYPE, blank=True)
    description = models.CharField(max_length=64)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('company_detail', args=[str(self.id)])

#customer profile list
class profile(models.Model):
    name = models.CharField(max_length=32)
    department = models.CharField(max_length=32, blank=True)
    title = models.CharField(max_length=32, blank=True)
    email = models.EmailField(max_length=128, blank=True)
    phone = models.CharField(max_length=32, blank=True)
    description = models.CharField(max_length=128, blank=True)
    company = models.ForeignKey('company', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('profile_detail', args=[str(self.id)])

#project list
class project(models.Model):
    company = models.ForeignKey('company', on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=32)
    product = models.CharField(max_length=32, blank=True)
    member = models.CharField(max_length=128, blank=True)
    date_start = models.DateField(null=True, blank=True)
    date_update = models.DateField(null=True, blank=True)
    STATUS_TYPE = (
        ('a', '拜訪'),
        ('b', '報價'),
        ('c', '訂單'),
        ('d', '設計中'),
        ('e', '交貨'),
        ('z', '結案'),
    )
    status = models.CharField(max_length=1, choices=STATUS_TYPE, blank=True)
    detail = models.TextField()
    technical = models.CharField(max_length=256, blank=True)
    sales = models.CharField(max_length=256, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('project_detail', args=[str(self.id)])
    #replace \n etc to <br>
    #def detail_br(self):
    #    detail_br = self.detail
    #    for i in ["\r\n", "\n\r", "\n", "\r"]:
    #        detail_br = detail_br.replace(i, '<br>')
    #    return detail_br

#staff list
class staff(models.Model):
    name = models.CharField(max_length=32)
    DEPARTMENT_TYPE = (
        ('a', '技術部'),
        ('b', '業務部'),
        ('c', '管理部'),
    )
    department = models.CharField(max_length=1, choices=DEPARTMENT_TYPE, blank=True)
    boss0 = models.IntegerField(default=0, blank=True)
    boss1 = models.IntegerField(default=0, blank=True)
    boss2 = models.IntegerField(default=0, blank=True)

    class Meta:
        permissions = (("can_check_others", "has staffs work for self"),)

    def __str__(self):
        return self.name

#report list
class report(models.Model):
    staff_id = models.ForeignKey('staff', on_delete=models.SET_NULL, null=True)
    date_app = models.DateField(null=True, blank=True)
    work = models.TextField()
    date_start = models.DateField(null=True, blank=True)
    date_end = models.DateField(null=True, blank=True)
    b0 = models.IntegerField(default=0, blank=True)
    date_b0 = models.DateField(null=True, blank=True)
    b1 = models.IntegerField(default=0, blank=True)
    date_b1 = models.DateField(null=True, blank=True)
    b2 = models.IntegerField(default=0, blank=True)
    date_b2 = models.DateField(null=True, blank=True)
    STATUS_TYPE = (
        ('a', '暫存中'),
        ('b', '申請中'),
        ('c', '已核准'),
        ('d', '已駁回'),
    )
    status = models.CharField(max_length=1, choices=STATUS_TYPE, blank=True)
    comment = models.CharField(max_length=256, blank=True)

    def __str__(self):
        return str(self.staff_id)

    def get_absolute_url(self):
        return reverse('report_detail', args=[str(self.id)])

company/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

class ReportcheckForm(forms.Form):
    CHOICES = [('0', '駁回'), ('1', '核可')]
    check = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect, label="", label_suffix="", initial="0")
                                #widget=forms.Textarea(attrs={'class':'form-control transparent','rows':12, 'cols':14}))

    def clean_check(self):
        data = self.cleaned_data['check']
        # Check if there is no data.
        if len(data) < 1 :
            raise ValidationError(_("can't be empty!"))

        # Remember to always return the cleaned data.
        return data

company/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse_lazy, reverse
import logging
logger = logging.getLogger(__name__)
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required, permission_required
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
#from django.views.generic.edit import CreateView, UpdateView
import time, datetime
from django import forms
from django.db.models import Q

from .models import company, profile, project, staff, report
#staff dict
staff_dict = {"jonhuang":1, "jeremylai":2, "test1":3, "test2":4, "test3":5, "test4":6}
# Create your views here.
@login_required
def pw_change(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            logging.error('%s %s changed password.', request.user.pk, request.user.username)
            return redirect('home')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'company/pw_change.html', {'form': form})

#home page
@login_required
def home(request):
    logging.error('%s %s visited homepage.', request.user.pk, request.user.username)
    return render(request, 'company/home.html')

###company###
class company_list(LoginRequiredMixin, generic.ListView):
    model = company
    paginate_by = 20
    ordering='name'

class company_add(LoginRequiredMixin, generic.edit.CreateView):
    model = company
    fields = '__all__'
    success_url = reverse_lazy('company_list')

class company_update(LoginRequiredMixin, generic.edit.UpdateView):
    model = company
    fields = '__all__'
    success_url = reverse_lazy('company_list')

class company_detail(LoginRequiredMixin, generic.DetailView):
    model = company

###profile###
class profile_add(LoginRequiredMixin, generic.edit.CreateView):
    model = profile
    fields = '__all__'
    #set the initial value for company
    def get_initial(self):
        return {'company': self.kwargs['cpk']}
    #set the url after completion
    def get_success_url(self):
        return reverse_lazy('company_detail', kwargs={'pk':self.kwargs['cpk']})

class profile_update(LoginRequiredMixin, generic.edit.UpdateView):
    model = profile
    fields = '__all__'
    #set the url after completion
    def get_success_url(self):
        return reverse_lazy('company_detail', kwargs={'pk':self.kwargs['cpk']})

class profile_detail(LoginRequiredMixin, generic.DetailView):
    model = profile

###project###
class project_list(LoginRequiredMixin, generic.ListView):
    model = project
    paginate_by = 20
    ordering='-pk'

class project_add(LoginRequiredMixin, generic.edit.CreateView):
    model = project
    fields = '__all__'
    success_url = reverse_lazy('project_list')
    #set the initial value for dates
    def get_initial(self):
        return {'date_start': datetime.date.today(),
                'date_update': datetime.date.today()
        }

class project_update(LoginRequiredMixin, generic.edit.UpdateView):
    model = project
    fields = ['company', 'name', 'product', 'member', 'date_update', 'status', 'detail', 'technical', 'sales']
    success_url = reverse_lazy('project_list')
    initial = {'date_update': datetime.date.today()}

class project_detail(LoginRequiredMixin, generic.DetailView):
    model = project
    #replace \n etc to <br>
    def get_context_data(self, **kwargs): #**kwargs are dict parameter
        context = super().get_context_data(**kwargs)
        context['detail_br'] = context['project'].detail
        for i in ["\r\n", "\n\r", "\n", "\r"]:
            context['detail_br'] = context['detail_br'].replace(i, '<br>')
        return context

###report###
class report_list(LoginRequiredMixin, generic.ListView):
    #model = report
    #ordering='-pk'
    paginate_by = 20

    def get_queryset(self):
        return report.objects.filter(staff_id=staff_dict[self.request.user.get_username()]).order_by('-pk')

class report_add(LoginRequiredMixin, generic.edit.CreateView):
    model = report
    fields = ['staff_id', 'date_app', 'date_start', 'date_end', 'work', 'status', 'b0', 'b1', 'b2']
    success_url = reverse_lazy('report_list')

    #set the initial value for dates
    def get_initial(self):
        staff_id_now = staff_dict[self.request.user.get_username()]
        return {'date_app': datetime.date.today(),
                'status': 'a',
                'staff_id': staff_id_now,
                'b0': get_object_or_404(staff, pk=staff_id_now).boss0,
                'b1': get_object_or_404(staff, pk=staff_id_now).boss1,
                'b2': get_object_or_404(staff, pk=staff_id_now).boss2
        }
    #make date_app readonly
    def get_form(self, form_class = None):
        form = super().get_form(form_class)
        form.fields['date_app'].widget = forms.DateInput(attrs={'readonly':True})
        CHOICES = [('a', '暫存'), ('b', '申請')]
        form.fields['status'].widget = forms.RadioSelect(choices=CHOICES)
        form.fields['b0'].widget = forms.TextInput(attrs={'type':'hidden'})
        form.fields['b1'].widget = forms.TextInput(attrs={'type':'hidden'})
        form.fields['b2'].widget = forms.TextInput(attrs={'type':'hidden'})
        return form

class report_update(LoginRequiredMixin, generic.edit.UpdateView):
    model = report
    fields = ['staff_id', 'date_app', 'date_start', 'date_end', 'work', 'status']
    success_url = reverse_lazy('report_list')

    #set the initial value for dates
    def get_initial(self):
        return {'date_app': datetime.date.today(),
                'status': 'a',
        }
    #make date_app readonly
    def get_form(self, form_class = None):
        form = super().get_form(form_class)
        form.fields['date_app'].widget = forms.DateInput(attrs={'readonly':True})
        CHOICES = [('a', '暫存'), ('b', '申請')]
        form.fields['status'].widget = forms.RadioSelect(choices=CHOICES)
        return form

class report_detail(LoginRequiredMixin, generic.DetailView):
    model = report
    #replace \n etc to <br>
    def get_context_data(self, **kwargs): #**kwargs are dict parameter
        context = super().get_context_data(**kwargs)
        context['work_br'] = context['report'].work
        for i in ["\r\n", "\n\r", "\n", "\r"]:
            context['work_br'] = context['work_br'].replace(i, '<br>')
        #get boss names
        if context['report'].b0 != 0:
            context['boss0'] = get_object_or_404(staff, pk=context['report'].b0).name
        else:
            context['boss0'] = '--'
        if context['report'].b1 != 0:
            context['boss1'] = get_object_or_404(staff, pk=context['report'].b1).name
        else:
            context['boss1'] = '--'
        if context['report'].b2 != 0:
            context['boss2'] = get_object_or_404(staff, pk=context['report'].b2).name
        else:
            context['boss2'] = '--'
        return context

class report_check_list(PermissionRequiredMixin, generic.ListView):
    permission_required = 'company.can_check_others'
    template_name = 'company/report_check_list.html'
    paginate_by = 20

    def get_queryset(self):
        return report.objects.filter(Q(b0=staff_dict[self.request.user.get_username()])
                                    |Q(b1=staff_dict[self.request.user.get_username()])
                                    |Q(b2=staff_dict[self.request.user.get_username()])).order_by('-pk')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['staff_id_now'] = staff_dict[self.request.user.get_username()]
        return context

class report_check_detail(PermissionRequiredMixin, generic.DetailView):
    permission_required = 'company.can_check_others'
    model = report
    template_name = 'company/report_check_detail.html'
    #replace \n etc to <br>
    def get_context_data(self, **kwargs): #**kwargs are dict parameter
        context = super().get_context_data(**kwargs)
        context['work_br'] = context['report'].work
        for i in ["\r\n", "\n\r", "\n", "\r"]:
            context['work_br'] = context['work_br'].replace(i, '<br>')
        #get boss names
        if context['report'].b0 != 0:
            context['boss0'] = get_object_or_404(staff, pk=context['report'].b0).name
        else:
            context['boss0'] = '--'
        if context['report'].b1 != 0:
            context['boss1'] = get_object_or_404(staff, pk=context['report'].b1).name
        else:
            context['boss1'] = '--'
        if context['report'].b2 != 0:
            context['boss2'] = get_object_or_404(staff, pk=context['report'].b2).name
        else:
            context['boss2'] = '--'
        return context

from .forms import ReportcheckForm
@login_required
@permission_required('company.can_check_others')
def report_check(request, pk):
    if request.method == 'POST':
        item = get_object_or_404(report, pk=pk)
        form = ReportcheckForm(request.POST)
        # Check if the form is valid:
        if form.is_valid():
            # approved case
            if form.cleaned_data['check'] == '1':
                # process boss checked date
                if item.b0 == staff_dict[request.user.get_username()]:
                    item.date_b0 = str(datetime.date.today())
                elif item.b1 == staff_dict[request.user.get_username()]:
                    item.date_b1 = str(datetime.date.today())

company/templates/company/company_detail.html
{% extends "base_generic.html" %}
{% block title %}<a class="navbar-brand" href="#">Company Detail</a>{% endblock %}

{% block sidebar %}
              <li class="nav-item active">
                  <a class="nav-link" href="{% url 'company_list' %}">
                      <i class="nc-icon nc-icon nc-notes"></i>
                      <p>Customers</p>
                  </a>
              </li>
              <li>
                  <a class="nav-link" href="{% url 'project_list' %}">
                      <i class="nc-icon nc-single-copy-04"></i>
                      <p>Projects</p>
                  </a>
              </li>
              <li>
                  <a class="nav-link" href="{% url 'report_list' %}">
                      <i class="nc-icon nc-single-copy-04"></i>
                      <p>Reports</p>
                  </a>
              </li>

              <li class="nav-item active-pro">
                  <a class="nav-link" href="{% url 'pw_change' %}">
                      <i class="nc-icon nc-key-25"></i>
                      <p>Change Password</p>
                  </a>
              </li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
      <a href="{% url 'profile_add' company.pk %}"><p>Add new profile</p></a>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
      <div class="card strpied-tabled-with-hover">
          <div class="card-header ">
              <h4 class="card-title">{{company.name}} 公司人員</h4>
          </div>
          <div class="card-body table-full-width table-responsive">
              <table class="table table-hover table-striped">
                <thead>
                  <tr>
                    <th>姓名</th>
                    <th>部門</th>
                    <th>職稱</th>
                    <th>電話</th>
                    <th>動作</th>
                  </tr>
                </thead>
                <tbody>
                {% for profile in company.profile_set.all %}
                  <tr>
                    <td><a href="{% url 'profile_detail' profile.pk %}">{{profile.name}}</a></td>
                    <td>{{profile.department}}</td>
                    <td>{{profile.title}}</td>
                    <td>{{profile.phone}}</td>
                    <td><a href="{% url 'profile_update' company.pk profile.pk %}">Update</a></td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
          </div>
      </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
      <div class="card strpied-tabled-with-hover">
          <div class="card-header ">
              <h4 class="card-title">{{company.name}} 公司專案</h4>
          </div>
          <div class="card-body table-full-width table-responsive">
              <table class="table table-hover table-striped">
                <thead>
                  <tr>
                    <th>專案名稱</th>
                    <th>產品</th>
                    <th>團隊成員</th>
                    <th>狀態</th>
                    <th>開始日期</th>
                    <th>更新日期</th>
                  </tr>
                </thead>
                <tbody>
                {% for project in company.project_set.all %}
                  <tr>
                    <td><a href="{% url 'project_detail' project.pk %}">{{project.name}}</a></td>
                    <td>{{project.product}}</td>
                    <td>{{project.member}}</td>
                    <td>{{project.get_status_display}}</td>
                    <td>{{project.date_start}}</td>
                    <td>{{project.date_update}}</td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
          </div>
      </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
      <a href="{% url 'company_list' %}"><p>回公司清單</p></a>
    </div>
</div>
{% endblock %}

company/templates/company/company_form.html
{% extends "base_generic.html" %}
{% block title %}<a class="navbar-brand" href="#pablo">Customers</a>{% endblock %}

{% block sidebar %}
              <li class="nav-item active">
                  <a class="nav-link" href="{% url 'company_list' %}">
                      <i class="nc-icon nc-icon nc-notes"></i>
                      <p>Customers</p>
                  </a>
              </li>
              <li>
                  <a class="nav-link" href="{% url 'project_list' %}">
                      <i class="nc-icon nc-single-copy-04"></i>
                      <p>Projects</p>
                  </a>
              </li>
              <li>
                  <a class="nav-link" href="{% url 'report_list' %}">
                      <i class="nc-icon nc-single-copy-04"></i>
                      <p>Reports</p>
                  </a>
              </li>

              <li class="nav-item active-pro">
                  <a class="nav-link" href="{% url 'pw_change' %}">
                      <i class="nc-icon nc-key-25"></i>
                      <p>Change Password</p>
                  </a>
              </li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <form action="" method="post">
          {% csrf_token %}
          <table>
            {{form.as_table}}
          </table>
          <input type="submit" value="Submit">
          <p></p>
          <a href="javascript:history.back();"><p>Cancel</p></a>
        </form>
    </div>
</div>
{% endblock %}

company/templates/company/company_list.html
{% extends "base_generic.html" %}
{% block title %}<a class="navbar-brand" href="#pablo">Customers</a>{% endblock %}

{% block sidebar %}
              <li class="nav-item active">
                  <a class="nav-link" href="#">
                      <i class="nc-icon nc-icon nc-notes"></i>
                      <p>Customers</p>
                  </a>
              </li>
              <li>
                  <a class="nav-link" href="{% url 'project_list' %}">
                      <i class="nc-icon nc-single-copy-04"></i>
                      <p>Projects</p>
                  </a>
              </li>
              <li>
                  <a class="nav-link" href="{% url 'report_list' %}">
                      <i class="nc-icon nc-single-copy-04"></i>
                      <p>Reports</p>
                  </a>
              </li>

              <li class="nav-item active-pro">
                  <a class="nav-link" href="{% url 'pw_change' %}">
                      <i class="nc-icon nc-key-25"></i>
                      <p>Change Password</p>
                  </a>
              </li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
      <a href="{% url 'company_add' %}"><p>Add new company</p></a>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card strpied-tabled-with-hover">
            <div class="card-header ">
                <h4 class="card-title">Company List</h4>
            </div>
            <div class="card-body table-full-width table-responsive">
              {% if company_list %}
                <table class="table table-hover table-striped">
                  <thead>
                    <tr>
                      <th>公司</th>
                      <th>類別</th>
                      <th>地址</th>
                      <th>備註</th>
                      <th>動作</th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for company in company_list %}
                    <tr>
                      <td><a href="{% url 'company_detail' company.pk %}">{{company.name}}</a></td>
                      <td>{{company.get_type_display}}</td>
                      <td>{{company.address}}</td>
                      <td>{{company.description}}</td>
                      <td><a href="{% url 'company_update' company.pk %}">Update</a></td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
              {% else %}
                <p>No customer yet</p>
              {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

company/templates/company/project_detail.html
{% extends "base_generic.html" %}
{% block title %}<a class="navbar-brand" href="#">Projects</a>{% endblock %}

{% block sidebar %}
              <li>
                  <a class="nav-link" href="{% url 'company_list' %}">
                      <i class="nc-icon nc-icon nc-notes"></i>
                      <p>Customers</p>
                  </a>
              </li>
              <li class="nav-item active">
                  <a class="nav-link" href="{% url 'project_list' %}">
                      <i class="nc-icon nc-single-copy-04"></i>
                      <p>Projects</p>
                  </a>
              </li>
              <li>
                  <a class="nav-link" href="{% url 'report_list' %}">
                      <i class="nc-icon nc-single-copy-04"></i>
                      <p>Reports</p>
                  </a>
              </li>

              <li class="nav-item active-pro">
                  <a class="nav-link" href="{% url 'pw_change' %}">
                      <i class="nc-icon nc-key-25"></i>
                      <p>Change Password</p>
                  </a>
              </li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
      <div class="card strpied-tabled-with-hover">
          <div class="card-header ">
              <h4 class="card-title">{{ project.name }}</h4>
          </div>
          <div class="card-body table-full-width table-responsive">
              <table class="table table-hover table-striped">
                <thead>
                  <tr>
                    <th>公司</th>
                    <th>團隊成員</th>
                    <th>產品</th>
                    <th>狀態</th>
                    <th>開始日期</th>
                    <th>更新日期</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>{{project.company}}</td>
                    <td>{{project.member}}</td>
                    <td>{{project.product}}</td>
                    <td>{{project.get_status_display}}</td>
                    <td>{{project.date_start}}</td>
                    <td>{{project.date_update}}</td>
                  </tr>
                </tbody>
              </table>
              <table class="table table-hover table-striped">
                <thead>
                  <tr>
                    <th>詳細內容</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>{{detail_br|safe}}</td>
                  </tr>
                </tbody>
              </table>
              <table class="table table-hover table-striped">
                <thead>
                  <tr>
                    <th>技術資料檔案</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>{{project.technical}}</td>
                  </tr>
                </tbody>
                <thead>
                  <tr>
                    <th>業務資料檔案</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>{{project.sales}}</td>
                  </tr>
                </tbody>
              </table>
          </div>
      </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
      <a href="javascript:history.back();"><p>上一頁</p></a>
    </div>
</div>
{% endblock %}

company/templates/company/project_list.html
{% extends "base_generic.html" %}
{% block title %}<a class="navbar-brand" href="#pablo">Projects</a>{% endblock %}


{% block sidebar %}
              <li>
                  <a class="nav-link" href="{% url 'company_list' %}">
                      <i class="nc-icon nc-icon nc-notes"></i>
                      <p>Customers</p>
                  </a>
              </li>
              <li class="nav-item active">
                  <a class="nav-link" href="#">
                      <i class="nc-icon nc-single-copy-04"></i>
                      <p>Projects</p>
                  </a>
              </li>
              <li>
                  <a class="nav-link" href="{% url 'report_list' %}">
                      <i class="nc-icon nc-single-copy-04"></i>
                      <p>Reports</p>
                  </a>
              </li>

              <li class="nav-item active-pro">
                  <a class="nav-link" href="{% url 'pw_change' %}">
                      <i class="nc-icon nc-key-25"></i>
                      <p>Change Password</p>
                  </a>
              </li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
      <a href="{% url 'project_add' %}"><p>Add new project</p></a>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card strpied-tabled-with-hover">
            <div class="card-header ">
                <h4 class="card-title">Project List</h4>
            </div>
            <div class="card-body table-full-width table-responsive">
              {% if project_list %}
                <table class="table table-hover table-striped">
                  <thead>
                    <tr>
                      <th>編號</th>
                      <th>公司</th>
                      <th>專案名稱</th>
                      <th>團隊成員</th>
                      <th>狀態</th>
                      <th>更新日期</th>
                      <th>動作</th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for project in project_list %}
                    <tr>
                      <td><a href="{% url 'project_detail' project.pk %}">{{project.pk}}</a></td>
                      <td>{{project.company}}</td>
                      <td>{{project.name}}</td>
                      <td>{{project.member}}</td>
                      <td>{{project.get_status_display}}</td>
                      <td>{{project.date_start}}</td>
                      <td><a href="{% url 'project_update' project.pk %}">Update</a></td>
                    </tr>
                  {% endfor %}
                  </tbody>
                </table>
              {% else %}
                <p>No project yet</p>
              {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}